<App>
  <Frame
    id="$main"
    enableFullBleed={false}
    isHiddenOnDesktop={false}
    isHiddenOnMobile={false}
    padding="8px 12px"
    sticky={null}
    type="main"
  >
    <ModuleContainerWidget
      id="moduleContainer"
      backgroundColor="white"
      isGlobalWidgetContainer={true}
    >
      <Module
        id="testModule1"
        name="test-module"
        pageUuid="18494d42-50bf-11ee-a191-fbb7763b00df"
      />
    </ModuleContainerWidget>
  </Frame>
</App>
