return {
  "name": "DBQNEUROHEADACHESINCLUDINGMIGRAINEHEADACHES_1_NAMEOFCLAIMANTVETERAN",
  "ssn": "DBQNEUROHEADACHESINCLUDINGMIGRAINEHEADACHES_2_CLAIMANTVETERANSSOCIALSECURITYNUMBER",
  "dateOfExam": "DBQNEUROHEADACHESINCLUDINGMIGRAINEHEADACHES_3_DATEOFEXAMINATION"
}