<App>
  <Frame
    id="$main"
    enableFullBleed={false}
    isHiddenOnDesktop={false}
    isHiddenOnMobile={false}
    paddingType="normal"
    sticky={null}
    type="main"
  >
    <Text id="text1" value="# This is my app" verticalAlign="center" />
    <Image
      id="image1"
      horizontalAlign="center"
      src="https://placekitten.com/400/300"
    />
    <Module
      id="myModule1"
      name="my_module"
      pageUuid="8311a51c-518b-11ee-945f-bbc563be752f"
    />
  </Frame>
</App>
