id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-10-31T00:53:57.556Z
blockData:
  top: 48
  left: 48
  uuid: f69e5ef6-c64c-4b07-a0e4-94b8816f15e9
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: JavascriptQuery
  incomingOnSuccessEdges: []
