<GlobalFunctions>
  <GlobalWidgetQuery
    id="putInterstitial"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <GlobalWidgetQuery
    id="postConfig"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <GlobalWidgetQuery
    id="uploadImages"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <GlobalWidgetQuery
    id="patchInterstitial"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <JavascriptQuery
    id="saveDraft"
    isMultiplayerEdited={false}
    overrideOrgCacheForUserCache={false}
    query={include("./lib/saveDraft.js", "string")}
    resourceName="JavascriptQuery"
    showSuccessToaster={false}
  />
  <JavascriptQuery
    id="updateDraft"
    isMultiplayerEdited={false}
    overrideOrgCacheForUserCache={false}
    query={include("./lib/updateDraft.js", "string")}
    resourceName="JavascriptQuery"
    showSuccessToaster={false}
  />
  <GlobalWidgetQuery
    id="getInterstitialsPage"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <GlobalWidgetQuery
    id="getSelectedInterstitial"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <GlobalWidgetQuery
    id="hideCreateDrawerFrame"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <GlobalWidgetQuery
    id="setSelectedInterstitialName"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <GlobalWidgetQuery
    id="showViewDrawerFrame"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <SqlTransformQuery
    id="submitFormQuery"
    overrideOrgCacheForUserCache={false}
    query={include("./lib/submitFormQuery.sql", "string")}
    resourceName="SQL Transforms"
    resourceTypeOverride=""
  >
    <Event
      event="success"
      method="run"
      params={{
        ordered: [
          {
            src: "if (submitFormTrigger.value) {\n  createInterstitialForm.submit()\n}",
          },
        ],
      }}
      pluginId=""
      type="script"
      waitMs="0"
      waitType="debounce"
    />
  </SqlTransformQuery>
  <GlobalWidgetQuery
    id="setErrorMessage"
    defaultValue=""
    overrideOrgCacheForUserCache={false}
    resourceName="GlobalWidgetQuery"
    showSuccessToaster={false}
    value=""
  />
  <SqlTransformQuery
    id="scrollToErrorQuery"
    overrideOrgCacheForUserCache={false}
    query={include("./lib/scrollToErrorQuery.sql", "string")}
    resourceName="SQL Transforms"
    resourceTypeOverride=""
  >
    <Event
      event="success"
      method="run"
      params={{
        ordered: [
          {
            src: "if (errorMessage.value) {\n  createErrorMessageAlert.scrollIntoView()\n}",
          },
        ],
      }}
      pluginId=""
      type="script"
      waitMs="0"
      waitType="debounce"
    />
  </SqlTransformQuery>
  <Function
    id="isDisabled"
    funcBody={include("./lib/isDisabled.js", "string")}
  />
</GlobalFunctions>
