id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-10-31T00:51:03.408Z
blockData:
  top: 48
  left: 48
  uuid: 2549a8df-516d-42dd-b1ed-db19437b9eb6
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: JavascriptQuery
  incomingOnSuccessEdges: []
