<App>
  <Frame
    id="$main"
    enableFullBleed={false}
    isHiddenOnDesktop={false}
    isHiddenOnMobile={false}
    paddingType="normal"
    sticky={null}
    type="main"
  >
    <Text id="text1" value="# app-a" verticalAlign="center" />
    <Image
      id="image1"
      horizontalAlign="center"
      src="https://placekitten.com/400/300"
    />
    <Module
      id="modalM1"
      name="modal-m"
      pageUuid="6fb8d536-88a3-11ee-9bbd-3f1cb59d5735"
    />
  </Frame>
</App>
