customLibraries:
  array:
    - object:
        version: 4.17.21
        language: javascript
        variable: _
        codeString: |
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: lodash
    - object:
        version: 2.1.0
        language: javascript
        variable: numbro
        codeString: |
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: numbro
    - object:
        version: 5.3.2
        language: javascript
        variable: Papa
        codeString: |
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: papaparse
    - object:
        version: 0.5.23
        language: javascript
        variable: moment
        codeString: |
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: moment-timezone
    - object:
        version: 3.4.0
        language: javascript
        variable: uuid
        codeString: |
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: uuid
name: Jira AI Service Request Approval Workflow
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: |
          // lodash
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // numbro
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // papaparse
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // moment-timezone
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // uuid
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
hasProtectedTriggers: true
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: |
          {
            "BusinessCase": "Ren testing - AI request form appproval- call API use case",
            "SuccessMetrics": "*Success Metrics**",
            "ProcessImpact": "Process Impact*",
            "Urgency_Timeline": "Urgency/Timeline",
            "Will_AI_Service_access_enterprise_data": "No",
          "Have_you_completed_any_formal_training_on_Generative_AI": "Yes",
          "Have_you_read_the_AI_Policy_and_Data_Security_Policy": "No",
            "TicketNumber": "KAL-110103",
            "RequesterDepartment": "Engineering",
            "EmployeeID": "00107125",
            "ValueToBusiness": "Cost Savings, Innovation and Capability building, Employee Experience Enhancement, Insight or Decision Support",
            "Requester": "Renuka Tulachan",
            "RequesterEmail":"sghai@komatsu.com.au"
            
          }
        examplePathParams: ''
version: 43.0.9
workflowId: 6a9c1509-7b9d-4740-a9b1-55f50c357973
description: null
workflowTemplate:
  version: 3.323.0
